# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd

data = pd.read_csv('F:\\yiyuan\\zk_psoriasis_anno.csv',sep= ',',encoding="gb2312",header = None)
data_1 = data[data.iloc[:,1]==r'稳定期大斑块']
data_1 = data_1.drop([1],axis=1)
data_1=data_1.reset_index(drop=True)
df1_1 = pd.DataFrame(np.ones((data_1.shape[0],1))*1)
df1_2 = pd.DataFrame(np.ones((data_1.shape[0],1))*0)
df1_3 = pd.DataFrame(np.ones((data_1.shape[0],1))*0)
df1_4 = pd.DataFrame(np.ones((data_1.shape[0],1))*0)
df1_5 = pd.DataFrame(np.ones((data_1.shape[0],1))*0)
res_1 = pd.concat([data_1,df1_1,df1_2,df1_3,df1_4,df1_5],axis=1,join_axes=[data_1.index],ignore_index=True)
#print(res_1)
data_2 = data[data.iloc[:,1]==r'进展期斑块']
data_2 = data_2.drop([1],axis=1)
data_2=data_2.reset_index(drop=True)
df2_1 = pd.DataFrame(np.ones((data_2.shape[0],1))*0)
df2_2 = pd.DataFrame(np.ones((data_2.shape[0],1))*1)
df2_3 = pd.DataFrame(np.ones((data_2.shape[0],1))*0)
df2_4 = pd.DataFrame(np.ones((data_2.shape[0],1))*0)
df2_5 = pd.DataFrame(np.ones((data_2.shape[0],1))*0)
res_2 = pd.concat([data_2,df2_1,df2_2,df2_3,df2_4,df2_5],axis=1,join_axes=[data_2.index],ignore_index=True)
#print(res_2.head(20))
data_3 = data[data.iloc[:,1]==r'稳定期小斑块']
data_3 = data_3.drop([1],axis=1)
data_3=data_3.reset_index(drop=True)
df3_1 = pd.DataFrame(np.ones((data_3.shape[0],1))*0)
df3_2 = pd.DataFrame(np.ones((data_3.shape[0],1))*0)
df3_3 = pd.DataFrame(np.ones((data_3.shape[0],1))*1)
df3_4 = pd.DataFrame(np.ones((data_3.shape[0],1))*0)
df3_5 = pd.DataFrame(np.ones((data_3.shape[0],1))*0)
res_3 = pd.concat([data_3,df3_1,df3_2,df3_3,df3_4,df3_5],axis=1,join_axes=[data_3.index],ignore_index=True)
#print(res_3.head(20))
data_4 = data[data.iloc[:,1]==r'消退期斑块']
data_4 = data_4.drop([1],axis=1)
data_4=data_4.reset_index(drop=True)
df4_1 = pd.DataFrame(np.ones((data_4.shape[0],1))*0)
df4_2 = pd.DataFrame(np.ones((data_4.shape[0],1))*0)
df4_3 = pd.DataFrame(np.ones((data_4.shape[0],1))*0)
df4_4 = pd.DataFrame(np.ones((data_4.shape[0],1))*1)
df4_5 = pd.DataFrame(np.ones((data_4.shape[0],1))*0)
res_4 = pd.concat([data_1,df4_1,df4_2,df4_3,df4_4,df4_5],axis=1,join_axes=[data_4.index],ignore_index=True)
#print(res_4.shape)
data_5 = data[data.iloc[:,1]==r'红皮病型']
data_5 = data_5.drop([1],axis=1)
data_5=data_5.reset_index(drop=True)
df5_1 = pd.DataFrame(np.ones((data_5.shape[0],1))*0)
df5_2 = pd.DataFrame(np.ones((data_5.shape[0],1))*0)
df5_3 = pd.DataFrame(np.ones((data_5.shape[0],1))*0)
df5_4 = pd.DataFrame(np.ones((data_5.shape[0],1))*0)
df5_5 = pd.DataFrame(np.ones((data_5.shape[0],1))*1)
res_5 = pd.concat([data_5,df5_1,df5_2,df5_3,df5_4,df5_5],axis=1,join_axes=[data_5.index],ignore_index=True)
#print(res_5.head(10))
fr = [res_1,res_2,res_3,res_4,res_5]
result = pd.concat(fr,ignore_index=True)
#print(result)
#print(result.head(10))
from sklearn.utils import shuffle
df = shuffle(result)
df=df.reset_index(drop=True)
df.to_csv('F:\\yiyuan\\银屑病\\pifu.txt',header=None,sep=' ',index=None)
print(df.shape)
print(df)